environment cleanup - assume XDKDEV, MSDEV abd MSCOM set in envronment Changes to support RTL... create def file if entry point given; allow def file to be provided, create dll

diff --git a/dx/windows/cc b/dx/windows/cc
--- a/dx/windows/cc
+++ b/dx/windows/cc
@@ -1,7 +1,8 @@
-XDKDEV="C:\Program Files\Hummingbird\Connectivity\7.10\Exceed\XDK"
-MSDEV="C:\Program Files\Microsoft SDK"
-MSVC="C:\Program Files\Microsoft Visual Studio"
-BINMODEDIR="C:\Program Files\Microsoft Visual Studio\VC98\Lib"
+export PATH="`cygpath \"$MSDEV\"`/bin:`cygpath \"$MSCOM\"`/bin:$PATH"
+export INCLUDE="$MSDEV/INCLUDE;XDKDEV/Include:$INCLUDE"
+export LIB="$MSDEV/LIB;$XDKDEV/Lib;$LIB"
+
+BINMODEDIR="$MSDEV\Lib"
 
 stdout=/tmp/stdo$$
 stderr=/tmp/stde$$
@@ -29,6 +30,7 @@ map=
 mounts=
 echo=0
 tmp="$MSDEV\Lib"
+oname=
 
 prelibs="$prelibs wsock32.lib"
 deflibs="$deflibs $LIBPATH kernel32.lib"
@@ -44,13 +46,13 @@ deflibs="$deflibs /NODEFAULTLIB:LIBC"
 link=1
 compile=1
 mkdep=0
-oset=0
-oname=
 dllflag=/MD
 dlllib=
 binmode=
 linkmodule=
 deffile=
+mkdll=0
+entryPt=DXEntry
 
 touch $stdout
 touch $stderr
@@ -68,12 +70,6 @@ cleanup() {
 			fi
 		fi
 	done
-
-
-#	if test -f $oname.exe ; then
-#		mv $oname.exe foo
-#		mv foo $oname
-#	fi
         if test -f $stdout ; then
                 rm $stdout
         fi
@@ -86,6 +82,9 @@ cleanup() {
         if test -f bar$$ ; then
                 rm bar$$
         fi
+	if test -f tmp.def$$ ; then
+		rm tmp.def$$
+	fi
         if test -f foobar$$ ; then
                 rm foobar$$
         fi
@@ -93,16 +92,26 @@ cleanup() {
 
 trap 'cleanup; exit 1' 1 2 15
 
-for i in $* ; do
+while test ! "$1" = "" ; do
+	i=$1
 	case $i in 
+		-e)      shift
+			 if test "$1" = "" ; then
+			     echo "-e requires entry point argument"
+			     exit 1
+			 fi
+			 entryPt=$1;;
+		-shared) mkdll=1
+			 linkopts="$linkopts /dll" ;;
 		-staticRunTime)
 			 dlllib="libcmt.lib"
 			 dllflag="$dllflag /MT" ;;
 		-dllRunTime)
 			 dlllib="msvcrt.lib"
 			 dllflag="$dllflag /MD" ;;
-                -o)      # args="$args $i"
-                         oset=1 ;;
+                -o)      shift
+		         oname=$1
+                         args="$args /Fe$1" ;;
 		-map)	 map="/MAP" ;;
 		-Wp*)    dfile=`echo $i | sed "s/^.*\(.deps.*\)/ \1/"`
 			 mkdep=1 ;;
@@ -135,28 +144,24 @@ for i in $* ; do
 			 args="$args /E" ;;
 		-B)	 LIB="$LIB;$BINMODEDIR" 
 			 binmode="BINMODE.OBJ" ;;
-		-def*)	 tmp=`echo $i | sed "s/-def//"`
-			 tmp2=`cygpath -w -s "$tmp"`
-			 deffile="/DEF:\"$tmp2\"" ;;
+		-def)	 shift
+			 if test "$1" = ""; then
+			     echo "-def requires def file name argument"
+			     exit 1
+			 fi
+			 deffile=/DEF:\"$1\" ;;
 		-module) dllflag="$dllflag /LD"
 			 linkmodule="/DLL /EXPORT:DXEntry" ;;
-                 *)      if test $oset = 1 ; then
-                             oname=$i
-                             args="$args /Fe$i"
-                             oset=0
-                         else
-                             args="$args $i"
-                         fi ;;
+                 *)      args="$args $i" ;;
 
 
 	esac
+	shift
 done
 
 tmp=`cygpath -a --windows "$MSDEV/Include"`
 msincs="/I\"$tmp\""
 incpath="$incpath $msincs"
-# echo $incpath
-# incpath=`echo "$incpath" | sed 's/\\\\/\\\\\\\\/'g`
 
 if test $mkdep = 1; then
     if test -e foo$$ ; then
@@ -190,6 +195,16 @@ if test $mkdep = 1; then
 fi
 
 if test $compile = 1 ; then
+    
+    if test $mkdll = 1 ; then
+	if test ! X"$deffile" = X"" ; then
+	    echo "cannot specify both a def file and a DLL entry point"
+	    exit 1
+	fi
+	echo EXPORTS > tmp.def$$
+	echo $entryPt >> tmp.def$$
+        deffile=/DEF:tmp.def$$
+    fi
 
     if test $link = 1 ; then
 	cmd="cl -nologo $incpath $msincs $defs $undefs $args $cfiles $dllflag /link $libpath $prelibs $libs $deflibs $dlllib $map $binmode $linkopts $linkmodule $deffile" 
@@ -218,6 +233,10 @@ if test $compile = 1 ; then
 	fi
     else
 	err=1
+    fi
+
+    if test $mkdll = 1 -a -f ${oname}.exe ; then
+	mv ${oname}.exe ${oname}.dll
     fi
 
     if test $link = 1 ; then
diff --git a/dx/windows/cxx b/dx/windows/cxx
--- a/dx/windows/cxx
+++ b/dx/windows/cxx
@@ -1,7 +1,8 @@
-XDKDEV="C:\Program Files\Hummingbird\Connectivity\7.10\Exceed\XDK"
-MSDEV="C:/Program Files/Microsoft SDK"
-MSVC="C:/Program Files/Microsoft Visual Studio"
-BINMODEDIR="C:\Program Files\Microsoft Visual Studio\VC98\Lib"
+export PATH="`cygpath \"$MSDEV\"`/bin:`cygpath \"$MSCOM\"`/bin:$PATH"
+export INCLUDE="$MSDEV/INCLUDE;XDKDEV/Include:$INCLUDE"
+export LIB="$MSDEV/LIB;$XDKDEV/Lib;$LIB"
+
+BINMODEDIR="$MSDEV\Lib"
 
 stdout=/tmp/stdo$$
 stderr=/tmp/stde$$
@@ -28,6 +29,8 @@ cfiles=
 mounts=
 echo=0
 tmp="$MSDEV\Lib"
+mkdll=0
+entryPt=DXEntry
 
 prelibs="$prelibs wsock32.lib"
 
@@ -75,10 +78,9 @@ cleanup() {
 		fi
 	done
 
-#	if test -f $oname.exe ; then
-#		mv $oname.exe foo
-#		mv foo $oname
-#	fi
+	if test -f tmp.def$$ ; then
+		rm tmp.def$$
+	fi
 	if test -f $stdout ; then
 		rm $stdout
 	fi
@@ -98,16 +100,26 @@ cleanup() {
 
 trap 'cleanup; exit 1' 1 2 15
 
-for i in $* ; do
+while test ! "$1" = "" ; do
+	i=$1
 	case $i in 
+                -e)      shift
+                         if test "$1" = "" ; then
+                             echo "-e requires entry point argument"
+                             exit 1
+                         fi
+                         entryPt=$1;;
+                -shared) mkdll=1
+                         linkopts="$linkopts /dll" ;;
                 -staticRunTime)
                          dlllib="libcmt.lib"
                          dllflag="-MT" ;;
                 -dllRunTime)
                          dlllib="msvcrt.lib"
                          dllflag="-MD" ;;
-                -o)      # args="$args $i"
-                         oset=1 ;;
+                -o)      shift
+                         oname=$1 
+			 args="$args /Fe$1" ;;
 		-map)	 map="/MAP" ;;
                 -Wp*)    dfile=`echo $i | sed "s/^.*\(.deps.*\)/ \1/"`
                          mkdep=1 ;;
@@ -150,27 +162,23 @@ for i in $* ; do
                          cp $i $fname
                          delfiles="$delfiles $fname"
 			 cfiles="$cfiles $fname" ;;
-                -def*)   tmp=`echo $i | sed "s/-def//"`
-                         tmp2=`cygpath -w -s "$tmp"`
-                         deffile="/DEF:\"$tmp2\"" ;;
+                -def)    shift
+                         if test "$1" = ""; then
+                             echo "-def requires def file name argument"
+                             exit 1
+                         fi
+                         deffile=/DEF:\"$1\" ;;
                 -module) dllflag="$dllflag /LD"
                          linkmodule="/DLL /EXPORT:DXEntry" ;;
-                *)       if test $oset = 1 ; then
-                             oname=$i
-                             args="$args /Fe$i"
-                             oset=0
-			 else
-			     args="$args $i"
-                         fi ;;
+                *)	 args="$args $i" ;;
 	esac
+	shift
 done
 
 
 tmp=`cygpath -a --windows "$MSDEV/Include"`
 msincs="/I\"$tmp\""
 incpath="$incpath $msincs"
-#incpath=`echo $incpath | sed 's/\\\\/\\\\\\\\/g'`
-#libpath=`echo $libpath | sed 's/\\\\/\\\\\\\\/g'`
 
 if test $mkdep = 1; then
     if test -f foo$$ ; then
@@ -209,6 +217,16 @@ fi
 
 if test $compile = 1
 then
+    
+    if test $mkdll = 1 ; then
+	if test ! X"$deffile" = X"" ; then
+	    echo "cannot specify both a def file and a DLL entry point
+	    exit 1
+	fi
+	echo EXPORTS > tmp.def$$
+	echo entryPt >> tmp.def$$
+	deffile=/DEF:tmp.def$$
+    fi
 
     if test $link = 1 ; then
 	cmd="cl -nologo $incpath $msincs $defs $undefs $args $cfiles $dllflag /link $libpath $prelibs $libs $deflibs $dlllib $map $binmode $linkopts $linkmodule $deffile" 
@@ -237,6 +255,10 @@ then
         fi
     else
         err=1
+    fi
+
+    if test $mkdll = 1 -a -f ${oname}.exe ; then
+	mv ${oname}.exe ${oname}.dll
     fi
 
     if test $link = 1 ; then
